# 规范文档参考:
# 中文：https://github.com/Serverless-Devs/Serverless-Devs/blob/master/spec/zh/0.0.2/serverless_package_model/package_model.md#应用模型规范
# English: https://github.com/Serverless-Devs/Serverless-Devs/blob/master/spec/en/0.0.2/serverless_package_model/package_model.md#Application-model-specification
# --------------
# Package 开发发布最佳实践:
#   - [社区讨论 #62](https://github.com/Serverless-Devs/Serverless-Devs/discussions/62);
#   - [社区讨论 #407](https://github.com/Serverless-Devs/Serverless-Devs/discussions/407);
#   - [社区讨论 #439](https://github.com/Serverless-Devs/Serverless-Devs/discussions/439);

Type: Application
Name: shltest
Provider:
  - 阿里云
Version: 0.0.43
Description: 简短的描述/介绍
HomePage: 项目首页地址
Tags: #标签详情
  - 部署函数
  - 部署组件
Category: 新手入门 # 基础云服务/Web框架/Web应用/人工智能/音视频处理/图文处理/监控告警/大数据/IoT/新手入门/其他
Parameters:
  type: object
  additionalProperties: false # 不允许增加其他属性
  required: # 必填项
    - region
    - serviceName
    - kafkaInstanceID
    - kafkaEndpoint
    - vpcId
    - vswitchId
    - securityGroupId
  properties:
    region:
      title: 地域
      type: string
      default: cn-hangzhou
      description: 创建应用所在的地区
      enum:
        - cn-beijing
        - cn-hangzhou
        - cn-shanghai
    serviceName:
      title: 服务名
      type: string
      default: web-framework-${default-suffix}
      pattern: "^[a-zA-Z_][a-zA-Z0-9-_]{0,127}$"
      description: 只能包含字母、数字、下划线和中划线。不能以数字、中划线开头。长度在 1-128 之间。
    kafkaInstanceID:
      title: kafka instance id
      type: string
      default: alikafka_post-cn-****
      description: kafka 实例 id
      x-kafka:
        denpendency:
          - region
    kafkaEndpoint:
      title: kafka endpoint
      type: string
      default: alikafka-post-cn-***-1-vpc.alikafka.aliyuncs.com:9092
      description: kafka endpoint, 可以从 kafka 控制台获取
    vpcId:
      title: kafka 实例所在 vpc id
      type: string
      default: vpc-******
      description: VPC id。请注意需要填写函数计算支持的 az
    vswitchId:
      title: vswitchId
      type: string
      default: vsw-*****
      description: vpc 中 vswitch id，用于内网访问 kafka
    securityGroupId:
      title: security group id
      type: string
      default: sg-*****
      description: vpc 下安全组 id，用于内网访问 kafka
    # internetAccess:
    #   type: boolean
    #   title: 允许公网访问
    #   description: 配置服务中的函数是否可以访问互联网
    #   default: true
    # secret:
    #   type: secret
    #   title: 应用管理员密码
    #   pattern: "^[a-zA-Z0-9]{8,30}$"
    #   description: 字母、数字、下划线，长度8-30位
    #   default: secretsecret1
    # acrRegistry:
    #   title: 镜像仓库
    #   type: string
    #   examples:
    #     [
    #       "registry.cn-hangzhou.aliyuncs.com/fc-demo/custom-springboot-function:v0.1",
    #     ]
    #   description: 镜像仓库地址，需要在 https://cr.console.aliyun.com/ 中开通服务、创建仓库以及设置访问凭证
    #   x-acr:
    #     type: "select"
    Timestamp:
      title: 时间戳
      type: string
      description: 时间戳，仅当参数Offset取值为CONSUME_FROM_TIMESTAMP时，该参数有效
    # longtitle:
    #   type: string
    #   title: longlonglonglonglonglonglonglonglonglongtitle
    #   description: 很长很长的描述
    # city:
    #   title: 城市
    #   type: string
    #   default: 杭州
    #   description: 创建应用所在的城市
    # vpcConfigType:
    #   title: VPC网络配置
    #   type: string
    #   description: 配置服务中函数使用的网络，例如配置函数是否可以访问公网，是否可以访问 VPC 中的资源等。
    #   enum:
    #     - auto
    #     - 自定义配置
    # vpcID:
    #   title: vpcID
    #   type: string
    #   default: "xx-vpcID"
    #   description: vpcID
    # securityGroupID:
    #   title: securityGroupID
    #   type: string
    #   default: "xx-securityGroupID"
    #   description: securityGroupID
    # vswitchID:
    #   title: vswitchID
    #   type: string
    #   default: "xx-vswitchID"
    #   description: vswitchID
