edition: 1.0.0 #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: functionApp #  项目名称
access: "{{access}}" #  秘钥别名

services:
  function-test: #  服务名称
    component: fc # 组件名称
    props: #  组件的属性值
      region: "{{region}}"
      service:
        name: "{{ serviceName }}"
        description: 欢迎使用ServerlessTool
        internetAccess: "{{ internetAccess }}"
        {{if vpcConfigType === 'auto'}}
        vpcConfig: auto
        {{else}}
        vpcConfig: # VPC配置, 配置后function可以访问指定VPC
          vpcId: "{{vpcID}}" # VPC ID
          securityGroupId: "{{securityGroupID}}" # 安全组ID
          vswitchIds: # 交换机 ID 列表
            - "{{vswitchID}}"
        {{/if}}
      function:
        name: serverless_demo_nodejs12
        description: 这是一个Nodejs12的测试案例
        codeUri: ./
        handler: index.handler
        memorySize: 128
        runtime: nodejs12
        timeout: 5
        environmentVariables:
          secret: "{{secret}}"
          secret2: "{{secret2}}"
        time: "{{time | timestamp}}"
      triggers:
        - name: EBRocketMQ
          type: eventbridge
          config:
            triggerEnable: true
            asyncInvocationType: false
            eventRuleFilterPattern: "{}"
            eventSourceConfig:
              eventSourceType: RocketMQ
              eventSourceParameters:
                sourceRocketMQParameters:
                  RegionId: "{{ region}}"
                  InstanceId: "{{ InstanceId}}"
                  Tag: "{{ Tag }}"
                  Topic: "{{ Topic }}"
                  Offset: "{{ Offset }}"
                  Timestamp: {{ Timestamp }} #只有在offset为CONSUME_FROM_TIMESTAMP时，该参数有效，其余情况下任意设置
                  GroupID: "{{ GroupID}}"
      # triggers:
      #   - name: cron-tab-trigger
      #     type: timer
      #     config:
      #       payload: |
      #         {
      #           "city": "{{city}}",
      #         }
      #       cronExpression: "@every 1m"
      #       enable: true
